[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.2.1",
    "pymongo>=4.13.0",
    "python-telegram-bot>=22.1",
    "requests>=2.32.3",
    "telegram>=0.0.1",
]
