[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow>=8.0.0",
    "pymongo>=4.0.0",
    "python-telegram-bot==13.15",
    "requests>=2.25.0",
]
